# version of docker-compose installed by chef only supports v2 of compose
version: '2.0'
services:
  nginx:
    image: nginx:1.21.3
    ports: 
      - 443:443
    volumes: 
      - /opt/machete/config/nginx/conf.d/:/etc/nginx/conf.d/
      - /opt/machete/secrets:/app/certs
      - /opt/machete/logs/nginx:/app/api/logs
    networks:
      - machete-bridge
  dotnet:
    env_file: "./env_variables.conf"
    image: "ndlonmachete/debian:1.15.29"
    networks:  
      - machete-bridge
    ports: 
      - 127.0.0.1:4213:4213
    stdin_open: true
    tty: true
    volumes:
      - "/opt/machete/logs:/app/logs"
      - "/opt/machete/secrets:/app/certs"
      - /opt/machete/secrets/appsettings.json:/app/api/appsettings.json
  sqlserver:
    env_file: "./env_variables.conf"
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      ACCEPT_EULA: "Y"
    mem_limit: 5G
    networks:
      - machete-bridge
    ports:
      - 127.0.0.1:1433:1433
    volumes: 
      - "/opt/machete/sqlbackup:/var/opt/mssql/backups"
      - "/opt/machete/sqldata:/var/opt/mssql/data"
      - "/opt/machete/secrets:/var/opt/mssql/certs"
networks:
  machete-bridge:
    driver: bridge
# # https://docs.docker.com/storage/volumes/ <~ opts are under --mounts (type, source, destination, etc.)
