# version of docker-compose installed by chef only supports v2 of compose
# this is a TODO
version: "2"
services:
# # docker run -it --name machete --net=host --env-file machete1env.list ndlonmachete/debian:1.14.{build}
# # --net=host is left over from the last configuration; this would be a change:
  azurefuse:
    image: "ndlonmachete/azure-storage-fuse:0.0.3"
    tty: true
    stdin_open: true
    networks:  
      - machete-bridge
    devices: 
      - '/dev/fuse:/dev/fuse'
    cap_add:
      - SYS_ADMIN
    env_file: "./azurefuseenv.list"
    volumes: 
      - "/opt/machete/sqlbackup:/opt/sqlbackup"
      - "/opt/machete/sqlrestore:/opt/sqlrestore"
  machete:
    image: "ndlonmachete/debian:1.14.267"
    env_file: "./machete1env.list"
    networks:  
      - machete-bridge
    volumes:
      - "/opt/machete/secrets:/app/certs"
    tty: true
    stdin_open: true
# # docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=passw0rD!' --network bridge -p 1433:1433 --name sqlserver -d mcr.microsoft.com/mssql/server
# # https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-bash#pullandrun2017
# # https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-2017#persist
# # prod is on 2017-CU16-ubuntu at time of switch, this would be an upgrade
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
# # v3
#    deploy:
#      resources:
#        limits:
#          memory: 5G
    environment:
      SA_PASSWORD: "passw0rD!"
      ACCEPT_EULA: "Y"
# # v2
    mem_limit: 5G
    networks:
      - machete-bridge
    ports:
      - 1433:1433
    volumes: 
      - "/opt/machete/sqlbackup:/var/opt/mssql/backups"
      - "/opt/machete/sqldata:/var/opt/mssql/data"
      - "/opt/machete/secrets:/var/opt/mssql/certs"
networks:
  machete-bridge:
    driver: bridge
# # https://docs.docker.com/storage/volumes/ <~ opts are under --mounts (type, source, destination, etc.)
# # sql-databases opts 'src=/mnt/databases' <~ comment leftover from Chef, not sure if it really applies to anything
volumes:
  app-secrets: 
  sql-database-backups: 
  sql-database-restore: 
  sql-databases: 
