# version of docker-compose installed by chef only supports v2 of compose
# this is a TODO
version: "2"
services:
  machete:
    image: "ndlonmachete/debian:1.14.323"
    env_file: "./machete1env.list"
    networks:  
      - machete-bridge
    ports: 
      - 443:443
    stdin_open: true
    tty: true
    volumes:
      - "/opt/machete/secrets:/app/certs"
# # docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=passw0rD!' --network bridge -p 1433:1433 --name sqlserver -d mcr.microsoft.com/mssql/server
# # https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-bash#pullandrun2017
# # https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-2017#persist
# # prod is on 2017-CU16-ubuntu at time of switch, this would be an upgrade
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      SA_PASSWORD: "passw0rD!"
      ACCEPT_EULA: "Y"
# # v2
    mem_limit: 5G
    networks:
      - machete-bridge
    ports:
      - 1433:1433
    volumes: 
      - "/opt/machete/sqlbackup:/var/opt/mssql/backups"
      - "/opt/machete/sqldata:/var/opt/mssql/data"
      - "/opt/machete/secrets:/var/opt/mssql/certs"
networks:
  machete-bridge:
    driver: bridge
# # https://docs.docker.com/storage/volumes/ <~ opts are under --mounts (type, source, destination, etc.)
